# Default values for conference.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

app:
  image:
    repository: foxford/conference
    tag: ""

  resources:
    limits:
      cpu: 0.5
      memory: 500Mi
    requests:
      cpu: 0.1
      memory: 50Mi

  svc:
    audience: foobar
    credentials:
      # foobar:
      #   - subPath: private-key
      #     mountPath: /path/to/foobar/private/key

  audiences:
    - audience: foobar
      credentials:
        # foobar-der-credentials:
        #   - subPath: foobar-public-key
        #     mountPath: /path/to/foobar/public/key
      authn:
        # key: path/to/public_key.p8.der
      authz:
        # type: http
        # url: "https://authz.example.org/api/v1/authz"
      s3: yandex

  janusGroup:

migrations:
  image:
    repository: foxford/conference-migration
    tag: ""

  resources:
    limits:
      cpu: 0.1
      memory: 100Mi
    requests:
      cpu: 0.1
      memory: 100Mi

env:
  RUST_LOG: warn,conference=info,svc_utils=info,svc_utils::metrics=warn
  CACHE_ENABLED: 1
  CACHE_POOL_SIZE: 50
  CACHE_POOL_IDLE_SIZE: 5
  CACHE_POOL_TIMEOUT: 5
  CACHE_EXPIRATION_TIME: 300
  DATABASE_POOL_SIZE: 10
  DATABASE_POOL_IDLE_SIZE: 10
  DATABASE_POOL_TIMEOUT: 5
  DATABASE_POOL_MAX_LIFETIME: 43200

clusterService:
  ports:
    http: 8080
    internal_http: 8081  # Janus registry
    metrics: 8888

# internalService:
#   ports:
#     internal_http: 8081  # Janus registry

ingress:
  host: example.org

tls:
  secretName: tls-certificates

sentry:
  dsn: "https://foobar.example.org/"
