# Default values for conference.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

minReadySeconds: 5
preStopSleepSeconds: 5
networkTester:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/k8s-network-tester
    tag: latest

app:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/conference

  resources:
    requests:
      cpu: 0.1
      memory: 50Mi

migrations:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/conference-migration

  resources:
    requests:
      cpu: 0.1
      memory: 100Mi
    limits:
      memory: 200Mi

env:
  RUST_LOG: warn,conference=info,svc_utils=info,svc_utils::metrics=warn
  CACHE_ENABLED: 1
  CACHE_POOL_SIZE: 50
  CACHE_POOL_IDLE_SIZE: 5
  CACHE_POOL_TIMEOUT: 5
  CACHE_EXPIRATION_TIME: 300
  DATABASE_POOL_SIZE: 10
  DATABASE_POOL_IDLE_SIZE: 10
  DATABASE_POOL_TIMEOUT: 5
  DATABASE_POOL_MAX_LIFETIME: 43200

clusterService:
  ports:
    http: 8080
    internal_http: 8081  # Janus registry
    metrics: 8888

tls:
  secretName: tls-certificates

serviceMonitor:
  labels:
    release: kube-prometheus-stack

ingress:
  class: nginx
