# Default values for conference.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

container:
  image:
    repository: foxford/conference
    tag: ""

  resources:
    limits:
      cpu: 0.5
      memory: 500Mi
    requests:
      cpu: 0.1
      memory: 50Mi

sentry:
  dsn: "https://foobar.example.org/"

svc:
  audience: svc.services
  credentials:
    # svc-secret:
    #   - subPath: private-key
    #     mountPath: /path/to/svc/private/key

audiences:
  - audience: foo.bar
    credentials:
      foobar-der-credentials:
        - subPath: foobar-public-key
          mountPath: /path/to/foobar/public/key
    authn:
      key: path/to/public_key.p8.der
    authz:
      type: http
      url: "https://authz.example.org/api/v1/authz"

env:
  RUST_LOG: warn,conference=info,svc_utils=info,svc_utils::metrics=warn
  CACHE_ENABLED: 1
  CACHE_POOL_SIZE: 50
  CACHE_POOL_IDLE_SIZE: 5
  CACHE_POOL_TIMEOUT: 5
  CACHE_EXPIRATION_TIME: 300
  DATABASE_POOL_SIZE: 15
  DATABASE_POOL_IDLE_SIZE: 15
  DATABASE_POOL_TIMEOUT: 5
  DATABASE_POOL_MAX_LIFETIME: 43200

config:
  janus_group:

service:
  type: ClusterIP
  ports:
    http: 8082
    metrics: 8080

ingress:
  host: example.org
  tls:
    secretName: tls-certificates

loadBalancer:
  annotations:
