[general]
vacuum_interval = 10000

[recordings]
enabled = false
directory = "/recordings"
delete_records = true

[constraint.writer]
default_video_bitrate = 300000
max_video_remb = 1000000
audio_bitrate = 30000

[upload]
backends = []
