apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: netologygroup/conference-migration
    docker:
      dockerfile: docker/migration.dockerfile
  - image: netologygroup/conference
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
    tryImportMissing: true
deploy:
  kustomize:
    paths:
    - deploy/k8s/overlays/ns
