apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: foxford/conference-migration
    docker:
      dockerfile: docker/migration.dockerfile
  - image: foxford/conference
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
    tryImportMissing: true
deploy:
  helm:
    releases:
    - name: conference
      chartPath: chart
      artifactOverrides:
        app.image: foxford/conference
        migrations.image: foxford/conference-migration
      imageStrategy:
        helm: {}
      valuesFiles:
        - deploy/values.yaml
