apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
  - image: netologygroup/conference
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.IMAGE_TAG}}'
  local:
    push: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
    - k8s/conference.yaml