apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image: netologygroup/conference-migration
      docker:
        dockerfile: docker/migration.dockerfile
    - image: netologygroup/conference
      docker:
        dockerfile: docker/Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.IMAGE_TAG}}'
  local:
    push: true
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - deploy/k8s/conference.yaml
      - deploy/k8s/conference-config.yaml
      - deploy/k8s/conference-environment.yaml
      - deploy/k8s/conference-headless.yaml
