apiVersion: v1
kind: Service
metadata:
  name: {{ include "conference.fullname" . }}-headless
  labels:
    {{- include "conference.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "conference.selectorLabels" . | nindent 4 }}
  clusterIP: None
