apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "conference.name" . }}-pdb
  labels:
    {{- include "conference.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "conference.selectorLabels" . | nindent 6 }}
