apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-servicemonitor
  labels:
    {{- include "conference.labels" . | nindent 4 }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    port: metrics
    scheme: http
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: {{ .Chart.Name }}
  selector:
    matchLabels:
      {{- include "conference.selectorLabels" . | nindent 6 }}
