apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: conference
spec:
  serviceName: conference-headless
  selector:
    matchLabels:
      app: conference
  replicas: 1
  template:
    metadata:
      labels:
        app: conference
    spec:
      containers:
        - name: conference
          image: netologygroup/conference
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: conference-environment
                  key: RUST_LOG
            - name: DATABASE_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: conference-environment
                  key: DATABASE_POOL_SIZE
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-conference-credentials
                  key: database_url
            - name: APP_AGENT_LABEL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              mountPath: /app/App.toml
              subPath: App.toml
            - name: iam
              mountPath: /app/data/keys/iam.public_key.p8.der
              subPath: iam.public_key
            - name: svc
              mountPath: /app/data/keys/svc.private_key.p8.der
              subPath: svc.private_key
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: config
          configMap:
            name: conference-config
        - name: iam
          secret:
            secretName: iam-pkcs8-der-credentials
        - name: svc
          secret:
            secretName: svc-pkcs8-der-credentials
