kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "conference.name" . }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods/status"]
    verbs: ["get"]
