---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
{{- if eq .Values.werf.env "production" }}
  annotations:
    "werf.io/replicas-on-creation": {{ pluck .Values.werf.env .Values.app.hpa.min_replicas | first | default .Values.app.hpa.min_replicas._default }}
{{- end }}
spec:
  serviceName: {{ .Chart.Name }}-headless
  replicas: {{ pluck .Values.werf.env .Values.app.hpa.min_replicas | first | default .Values.app.hpa.min_replicas._default }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        checksum/config-app: {{ include (print $.Template.BasePath "/09-cm-app.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
      - name: registrysecret
      initContainers:
{{ include "wait_postgres" . | indent 6 }}
{{ include "wait_redis" . | indent 6 }}
{{ include "psql_check_db" . | indent 6 }}
      containers:
      - name: event
        image: {{ .Values.werf.image.event }}
        resources:
          requests:
            cpu: {{ pluck .Values.werf.env (index .Values.app.resources.cpu .Values.global.org .Values.global.app) | first | default (index .Values.app.resources.cpu .Values.global.org .Values.global.app)._default }}
            memory: {{ pluck .Values.werf.env (index .Values.app.resources.memory .Values.global.org .Values.global.app) | first | default (index .Values.app.resources.memory .Values.global.org .Values.global.app)._default }}
          limits:
            memory: {{ pluck .Values.werf.env (index .Values.app.resources.memory .Values.global.org .Values.global.app) | first | default (index .Values.app.resources.memory .Values.global.org .Values.global.app)._default }}
        env:
{{- include "envs" . | indent 8 }}
        ports:
        - containerPort: {{ pluck .Values.werf.env .Values.app.port.number | first | default .Values.app.port.number._default }}
          name: {{ pluck .Values.werf.env .Values.app.port.name | first | default .Values.app.port.name._default }}
        volumeMounts:
{{- include "volumeMounts" . | indent 8 }}
      volumes:
{{- include "volumes" . | indent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-headless
spec:
  selector:
    app: {{ .Chart.Name }}
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    prometheus.deckhouse.io/target: rust
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: {{ pluck .Values.werf.env .Values.app.port.name | first | default .Values.app.port.name._default }}
      port: {{ pluck .Values.werf.env .Values.app.port.number | first | default .Values.app.port.number._default }}
