{{- if eq .Values.werf.env "production" }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
{{- end }}