name: Build dev artifacts

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  build-chart:
    uses: foxford/reusable-workflows/.github/workflows/build-dev-chart.yml@master
    secrets:
      helm_registry_username: ${{ secrets.YANDEX_HELM_USERNAME }}
      helm_registry_password: ${{ secrets.YANDEX_HELM_PASSWORD }}

  build-image:
    uses: foxford/reusable-workflows/.github/workflows/build-dev-image.yml@master
    secrets:
      docker_registry_username: ${{ secrets.YANDEX_DOCKER_USERNAME }}
      docker_registry_password: ${{ secrets.YANDEX_DOCKER_PASSWORD }}
