name: Build release artifacts

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*.*.*'

jobs:
  build-chart:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    uses: foxford/reusable-workflows/.github/workflows/build-release-chart.yml@master
    secrets:
      helm_registry_username: ${{ secrets.YANDEX_HELM_USERNAME }}
      helm_registry_password: ${{ secrets.YANDEX_HELM_PASSWORD }}

  build-image:
    if: startsWith(github.ref, 'refs/tags/')
    uses: foxford/reusable-workflows/.github/workflows/build-release-image.yml@master
    secrets:
      docker_registry_username: ${{ secrets.YANDEX_DOCKER_USERNAME }}
      docker_registry_password: ${{ secrets.YANDEX_DOCKER_PASSWORD }}
    with:
      repository: cr.yandex/crp1of6bddata8ain3q5/conference
