name: CI

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v1
    - name: clippy
      run: cargo clippy -- -D warnings
    - name: fmt
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test --verbose
