name: Deploy

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Namespace'
        required: true
        default: 'testing01'
      version:
        description: 'Commit/tag/branch'
        required: false
      configuration_branch:
        description: 'Configuration branch to use'
        required: true
        default: 'master'

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.version }}
        fetch-depth: 0
    - uses: satackey/action-docker-layer-caching@46d2c640b1d8ef50d185452ad6fb324e6bd1d052
      continue-on-error: true
    - name: Deploy
      run: |
        for NAMESPACE in $NAMESPACES; do
          NAMESPACE=$NAMESPACE BRANCH=$BRANCH ./deploy.init.sh && NAMESPACE=$NAMESPACE ./deploy/github-actions-run.sh
        done
      env:
        NAMESPACES: ${{ github.event.inputs.namespace }}
        BRANCH: ${{ github.event.inputs.configuration_branch }}
        KUBE_TOKEN_TESTING: ${{ secrets.KUBE_TOKEN_TESTING }}
        KUBE_SERVER_TESTING: ${{ secrets.KUBE_SERVER_TESTING }}
        OVPN_CONFIG: ${{ secrets.OVPN_CONFIG }}
        OVPN_CA: ${{ secrets.OVPN_CA }}
        OVPN_CERT: ${{ secrets.OVPN_CERT }}
        OVPN_KEY: ${{ secrets.OVPN_KEY }}
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        DOCKER_PASSWORD: ${{ secrets.YANDEX_DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.YANDEX_DOCKER_USERNAME }}

